version: '3'
services:
  web:
    build:
      dockerfile: ./docker_app/Dockerfile
      context: ../
    image: web-image
    volumes:
      - ../:/usr/src/app
    ports:
      - '8080:8080'

volumes:
  web-data:
